default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: incident_slack_bot_development

test:
  <<: *default
  database: incident_slack_bot_test

production:
  <<: *default
  database: incident_slack_bot_production
  username: yourapp
  password: <%= ENV['YOURAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['YOURAPP_DATABASE_HOST'] %>
  port: <%= ENV['YOURAPP_DATABASE_PORT'] %>
